import React, { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head'
import Image from 'next/image'

const MAX_CARD_NUMBER_LENGTH = 16; // Maximum number of characters for a credit card number

const TimeDisplay: React.FC = () => {
  const [time, setTime] = useState<string>('00:00');

  useEffect(() => {
    const interval = setInterval(() => {
      const date = new Date();
      const hours = date.getHours().toString().padStart(2, '0');
      const minutes = date.getMinutes().toString().padStart(2, '0');
      setTime(`${hours}:${minutes}`);
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  }, []);

  return (
    <div className='xs-12 md-6'>
      <div className="f-r">
        <p className="time">
          <span>{time[0]}</span>
          <span>{time[1]}</span>
          :
          <span>{time[3]}</span>
          <span>{time[4]}</span>
        </p>
      </div>
    </div>
  );
};

const Home: NextPage = () => {

  const [cardNumber, setCardNumber] = useState<number | string>(2412751234123456);
  const [cvvNumber, setCvvNumber] = useState<number | string>(327);
  const [expiryMonth, setExpiryMonth] = useState<number | string>("09");
  const [expiryYear, setExpiryYear] = useState<number | string>(22);
  const [password, setPassword] = useState<string>("");

  const handlePayment = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    // Process the payment using the form data
    const formData = {
      cardNumber,
      cvvNumber,
      expiryMonth,
      expiryYear,
      password,
    };
    console.log('Form Data:', formData);
  };

  const handleCardNumberChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const input = e.target.value.slice(0, MAX_CARD_NUMBER_LENGTH); // Limit the input to the maximum card number length
    setCardNumber(input);
  };

  return (
    <>
      <Head>
        <title>AceCoinPay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="xs-12">
        <div className="xs-12 md-8">

          <div className='xs-12 md-6'>
            <div className="f-l logo-part">
              <img src="/logo.png" alt="logo" id="logo"/><h2>AceCoinPay</h2>
            </div>
          </div>

        <TimeDisplay/>

          <form onSubmit={handlePayment}>

            <div className='credit-card xs-12'>
              <div className='c-n'>
                <label htmlFor="">Card Number</label>
                <span>Enter the 16-digit card number on the card</span>
              </div>
                <button className="edit">
                  <img src="/pen.png" alt="pen" className="pen"/>
                  Edit
                </button>
            </div>
            
            <div className="form-control xs-12 with-correct">
             <input
               type="text"
               className="xs-12"
               placeholder={cardNumber.toString()}
               value={cardNumber.toString()}
               onChange={handleCardNumberChange}
             />
             <img src="/correct.png" alt="check" className="correct" />
           </div>

            <div className="form-control xs-12">
              <div className="xs-12 md-6">
                <label htmlFor="">CVV Number</label>
                <span>Enter the 3 or 4 digit number on the card</span>
              </div>

              <div className="xs-12 md-6 with-dial">
                  <input
                    type="number"
                    placeholder={cvvNumber.toString()}
                    className="xs-12"
                    min={1}
                    value={cvvNumber.toString()}
                    onChange={(e) => setCvvNumber(e.target.value)}
                  />
                  <img src="/dial.png" alt='dial' className="dial" />
              </div>
            </div>

            <div className="form-control xs-12">
              <div className="xs-12 md-6">
                <label htmlFor="">Expiry Date</label>
                <span>Enter the expiration date of the card</span>
              </div>

              <div className="xs-12 md-6" style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
                <input
                  type="number"
                  placeholder={"09"}
                  className="xs-5"
                  max={12}
                  min={1}
                  value={expiryMonth.toString()}
                  onChange={(e) => setExpiryMonth(e.target.value)}
                />
                <span className="xs-2 t-c">/</span>
                <input
                  type="number"
                  placeholder={expiryYear.toString()}
                  className="xs-5"
                  min={1}
                  value={expiryYear.toString()}
                  onChange={(e) => setExpiryYear(e.target.value)}
                />
              </div>
            </div>

            <div className="form-control xs-12">
              <div className="xs-12 md-6">
                <label htmlFor="">Password</label>
                <span>Enter your dynamic password</span>
              </div>

              <div className="xs-12 md-6 with-dial">
              <input
                type="password"
                placeholder={"xxxxxxxxx"}
                className="xs-12"
                id="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                />
                <img src="/dial.png" alt='dial' className="dial" />
              </div>
            </div>

            <div className="form-control xs-12">
              <button className="xs-12 pay-now">Pay Now</button>
            </div>
          </form>
        </div>

        <div className="xs-12 md-3 md-off-1 right">
          <div className='blue'/>
          <div className="card-holder">
            <div className='backcard-holder'/>
            <div className="card">

              <div className="scannable-part">
                  <img src="/chip.png" alt="reader" id="reader"/>
                  <img src="/full-signal.png" alt="signal" id="signal"/>
              </div>

              <div className="card-content xs-12">

                <div className="top">
                  <p className="one">Jonathan Michael</p>
                  <p className="two"><span>●●●●</span> {cardNumber.toString().slice(-4)}</p>
                </div>

                <div className="bottom">
                 <p>{expiryMonth}/{expiryYear}</p>
                 <img src="/mastercard.png" alt="mastercard" />
               </div>

              </div>

            </div>

            <div className="payment-info xs-12">

              <div className="info-control xs-12 ">

                <div className="info xs-12">
                  <p className='xs-12 md-6 l'>Company</p>
                  <p className='xs-12 md-6 t-r b'><img src="/apple.png" alt="apple"/><span>Apple</span></p>
                </div>

                <div className="info xs-12">
                  <p className='xs-12 md-6 l'>Order Number</p>
                  <p className='xs-12 md-6 t-r b'>1266201</p>
                </div>

                <div className="info xs-12">
                  <p className='xs-12 md-6 l'>Product</p>
                  <p className='xs-12 md-6 t-r b'>Macbook Air</p>
                </div>

                <div className="info xs-12">
                  <p className='xs-12 md-6 l'>VAT (20%)</p>
                  <p className='xs-12 md-6 t-r b'>$100.00</p>
                </div>

              </div>

            <div>

          </div>
            </div>

            <div className='xs-12 total'>
              <button className="circle"/>
              <div className="bar"/>
              <button className="circle r"/>
            </div>

            <div className="xs-12 to-pay">
              <div className='xs-9'>
                <label>You have to Pay</label>
                <div className="amount">
                  <h2>549.<span>99</span></h2>
                  <span className="cur">USD</span>
                </div>
              </div>
              <div className="xs-3">
                <img src="/bill.png" alt="bill" className="bill"/>
              </div>
            </div>

          </div>
        </div>
      </main>

    </>
  )
}

export default Home
